image: docker:git

services:
  - docker:dind

stages:
  - test

before_script:
  - apk add --no-cache python py2-pip
  - pip install --no-cache-dir docker-compose

tests:
  stage: test
  script:
    - docker-compose run test
  coverage: '/Lines: +\d+\.\d+/'
  only:
    - branches
