FROM phpearth/php:7.2-cli

RUN apk add --no-cache composer php7.2-xdebug git zip
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.5.0/wait /usr/local/bin/wait
RUN chmod +x /usr/local/bin/wait

ADD docker-entrypoint.sh /
RUN chmod +x /docker-entrypoint.sh

WORKDIR /opt/app
COPY . /opt/app

RUN composer install

ENTRYPOINT ["/docker-entrypoint.sh"]

