FROM phpearth/php:7.3-cli

RUN apk add --no-cache git zip composer php7.3-xdebug php7.3-gd
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.5.0/wait /usr/local/bin/docker-compose-wait
RUN chmod +x /usr/local/bin/docker-compose-wait

COPY docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh

WORKDIR /opt/app
COPY . /opt/app

RUN composer install

ENTRYPOINT ["/docker-entrypoint.sh"]
